Improved git resource performance
Cyberwatch/HashThePlanet pull request #9
Opened 2021-11-02 11:01 UTC by JulienTD

## Description

This pull request improves the git resource's performance by getting the hash of only modified files between tags.

## Related Issue(s)
 
N/A

2021-11-02 14:18 UTC, bretfourbe commented on lib/resources/git_resource.py
> +            technology = url.split('.git')[0].split('/')[-1]
`technology` is not needed in this `with` block. Maybe you can move this before the next `with` block  ?

2021-11-02 14:27 UTC, JulienTD commented on lib/resources/git_resource.py
> +            for diffidx in commit_diff:
Done

2021-11-02 14:31 UTC, JulienTD commented on lib/resources/git_resource.py
>          except OSError as error:
Indeed, It is not necessary anymore :+1:

2021-11-02 15:34 UTC, polyedre commented on lib/resources/git_resource.py
> +        return file_list
Il y a la fonction `git.objects.fun.traverse_tree_recursive` qui fait exactement ça :)

2021-11-02 15:35 UTC, polyedre commented on lib/resources/git_resource.py
> +        return file_list
https://programtalk.com/python-examples/git.objects.fun.traverse_tree_recursive/

2021-11-03 12:09 UTC, JulienTD commented on lib/resources/git_resource.py
> +        return file_list
J'ai utilisé la fonction `commit.tree.traverse()` à la place parce qu'elle donne le blob hash sous format string et non binaire, de plus, elle est plus facile à utiliser parce qu'elle est déjà présente dans l'objet `commit` :rocket:

2021-11-09 14:50 UTC, polyedre requested changes
You can improve readability a bit more 😃

2021-11-09 14:50 UTC, polyedre commented on lib/resources/git_resource.py
> +        files: List[Tuple[FilePath, TagName, BlobHash]],
In order to increase readability, you could use a named dictionary or a dataclass to name objects represented with `Tuple[FilePath, TagName, BlobHash]` and `Tuple[FilePath, TagName, FileHash]` as these two structures are used multiple times.

2021-11-09 14:50 UTC, polyedre commented on lib/resources/git_resource.py
> +                file_content = subprocess.check_output(
Here you could add a comment explaining why subprocess is the right choice and why you don't use the Gitpython way of interacting with the command line.

2021-11-09 14:50 UTC, polyedre commented on lib/resources/git_resource.py
> +    def _get_diff_between_two_tags(tag_a: Tag, tag_b: Tag) -> List[Tuple[FilePath, TagName, BlobHash]]:
The name of the method does not seem to be accurate.

2021-11-09 14:50 UTC, polyedre commented on lib/resources/git_resource.py
> +        return diff_versions
You could use something like
```python
tag_names = list(map(lambda tag: tag.name, tags))
return tags[tag_names.index(first_version):tag_names.index(last_version)]
```

2021-11-09 17:29 UTC, polyedre approved these changes

2021-11-10 10:26 UTC, polyedre approved these changes

2021-11-10 10:26 UTC, polyedre commented on lib/resources/git_resource.py
> +BLOB_MODE = 33188
What is the meaning if this value ? Can you add a comment here or use a more explicit name ? :)

2021-11-13 19:54 UTC, fwininger commented
@JulienTD en attente de rebase en local.

2021-11-15 15:47 UTC, fwininger commented
@JulienTD toujours à rebase

2021-11-15 21:51 UTC, merged